### ISSUE TITLE
Hi! Can you support the mobilecus_fea_512.h5 file?Thanks a lot!!

### ISSUE THREAD

**Issue by xjrelc** [yimingkao/AIA_Final_DrowsyDriverDetection#2]

**Comment by xjrelc** [comment]
Sorry, Can you tell me how to get the mobilecus_512_train.h5 file?? I have got the mobilecus_fea_512.h5

**Comment by yimingkao** [comment]
Hi xjrelc, 
mobilecus_512_train.h5 file is the training result of mouthlstm_mtcnn.
Thank you!

**Comment by xjrelc** [comment]
Thanks a lot!!it's work successfully~and May you tell me the way or the standard to label the yawn degree??

**Comment by yimingkao** [comment]
Hi xjrelc,
We using the following rule to label it.
1. when he/she is starting to yawn, the degree is 1.
2. when he/she is about the maximum, the degree is 5.
3. when he/she stays the maximum, the degree is 5.
4. when he/she is starting to close the mouth, the degree changed from 5 to 1 (mouth is about closed).
5. 0 for other states.
Thank you!
